# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 15, 8, 58, 374689, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
