# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160723_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='draft',
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(),
        ),
    ]
