# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160808_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
