# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170621_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumb_image',
            field=models.ImageField(blank=True, height_field=150, null=True, upload_to=''),
        ),
    ]
