# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-22 01:03
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_thumb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.image_path),
        ),
    ]
