# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160811_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_time',
        ),
    ]
