# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160811_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
    ]
