# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160811_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_time',
        ),
    ]
