# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
